### ISSUE TITLE
Merge SPipes debug module

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-pipes#168]
Issue 1: 
On KODI forms AdvancedProgressListener returns Transaction already active! (we used to have this issue before):
```
java.lang.IllegalStateException: Transaction already active!
	at cz.cvut.kbss.jopa.transactions.EntityTransactionImpl.begin(EntityTransactionImpl.java:40)
	at cz.cvut.spipes.logging.AdvancedLoggingProgressListener.moduleExecutionFinished(AdvancedLoggingProgressListener.java:316)
	at cz.cvut.spipes.engine.ExecutionEngineImpl.lambda$_executePipeline$8(ExecutionEngineImpl.java:97)
	at cz.cvut.spipes.engine.ExecutionEngineImpl.lambda$fire$2(ExecutionEngineImpl.java:38)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at cz.cvut.spipes.engine.ExecutionEngineImpl.fire(ExecutionEngineImpl.java:36)
	at cz.cvut.spipes.engine.ExecutionEngineImpl._executePipeline(ExecutionEngineImpl.java:97)
	at cz.cvut.spipes.engine.ExecutionEngineImpl.lambda$_executePipeline$6(ExecutionEngineImpl.java:80)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
```

**Comment by blcham** [comment]
The issue still occurs when running SPipes in SPipes Editor.

**Comment by MSattrtand** [comment]
It's still occuring

<img width="1431" height="353" alt="Image" src="https://github.com/user-attachments/assets/9661dbf1-44c3-4fba-9679-36f35033f1ed" />

**Comment by blcham** [comment]
Can you describe how to reproduce it?

**Comment by MSattrtand** [comment]
I can not replicate it. I wasn't even trying to replicate it when I got the exception above - I was working on PR with executions' metadata and therefore executing a function in "Hello World", when this exception started to occur during the execution.

**Comment by MSattrtand** [comment]
I've found a way to replicate it consistently - run `skosify` function in `skosify.sms.ttl`
